# Generated by Django 2.1.5 on 2021-02-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarID', models.CharField(max_length=30)),
                ('Latitude', models.CharField(max_length=30)),
                ('Longitude', models.CharField(max_length=30)),
                ('Gas1', models.CharField(max_length=30)),
                ('Gas2', models.CharField(max_length=30)),
            ],
        ),
    ]
