# Generated by Django 2.1.5 on 2021-02-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gps',
            old_name='Gas1',
            new_name='gas1',
        ),
        migrations.RenameField(
            model_name='gps',
            old_name='Gas2',
            new_name='gas2',
        ),
    ]
